function [ x, y, z ] = filledCylinderAlt( radius, numSides, zHeights )
%FILLEDCYLINDERALT Creates a solid cylinder
%   Creates a solid cylinder at coordinates 0,0 for x,y.
%   Simplifies plotting the shape - uses the coordinates generated by the
%   cylinder function to generate top and base coordinates that can then
%   draw a 3D shape with surf, mesh or surface

% Create cylinder
[cx, cy, cz] = cylinder(radius, numSides);
cz(1,:) = zHeights(1);
cz(2,:) = zHeights(2);

% Setup top coordinates
topx = [cx(1,:); cx(1,:) * 0];
topy = [cy(1,:); cy(1,:) * 0];
topz = [cz(1,:); cz(1,:)];

% Setup base coordinates
basex = [cx(2,:); cx(2,:) * 0];
basey = [cy(2,:); cy(2,:) * 0];
basez = [cz(2,:); cz(2,:)];

% Combine top, middle, and base coordinates
x = [topx cx basex];
y = [topy cy basey];
z = [topz cz basez];

end